# Generated by Django 2.2 on 2019-06-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_order_orderitem_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
    ]
