# Generated by Django 2.2 on 2019-06-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0002_auto_20190613_1733'),
        ('plans', '0004_auto_20190613_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user_plan',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='UserPlan',
        ),
    ]
