# Generated by Django 2.2 on 2019-06-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('allowed_plans', models.ManyToManyField(to='plans.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=250)),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(max_length=300)),
                ('cover_image', models.ImageField(upload_to='')),
                ('entertainment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainments.Entertainment')),
            ],
        ),
    ]
