# Generated by Django 2.2 on 2019-06-11 01:37

from django.db import migrations, models
import django.db.models.deletion
import entertainments.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('allowed_plans', models.ManyToManyField(to='plans.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('song_name', models.CharField(max_length=250)),
                ('broadcaster', models.CharField(max_length=250)),
                ('released_date', models.DateField()),
                ('distribution_rights', models.TextField()),
                ('podcast_genre', models.CharField(choices=[('L', 'Life Advice'), ('F', 'Personal Finance'), ('A', 'Academic Performance'), ('O', 'Other')], default='Other', max_length=60)),
                ('cover_image', models.ImageField(upload_to='images/', validators=[entertainments.validators.image_validation_extension])),
                ('upload_podcast', models.FileField(upload_to='audios/', validators=[entertainments.validators.video_validation_extention])),
                ('entertainmentOption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainments.EntertainmentOption')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('song_name', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('released_date', models.DateField()),
                ('distribution_rights', models.TextField()),
                ('music_genre', models.CharField(choices=[('P', 'POP'), ('G', 'GOSPEL'), ('R', 'ROCK'), ('AP', 'AFRO POP'), ('RG', 'REGGAE'), ('H', 'HOUSE'), ('GN', 'GENERIC')], default='GENERIC', max_length=60)),
                ('cover_image', models.ImageField(upload_to='images/', validators=[entertainments.validators.image_validation_extension])),
                ('song', models.FileField(upload_to='audios/', validators=[entertainments.validators.video_validation_extention])),
                ('entertainmentOption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainments.EntertainmentOption')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=250)),
                ('film_type', models.CharField(choices=[('D', 'Drama'), ('S', 'Sitcom'), ('PD', 'Podcast Video'), ('SR', 'Series'), ('RS', 'Reality TV Show'), ('H', 'Home Entertainment')], default='Home Entertainment', max_length=60)),
                ('position', models.IntegerField()),
                ('details', models.TextField()),
                ('movie', models.FileField(upload_to='videos/', validators=[entertainments.validators.video_validation_extention])),
                ('cover_image', models.ImageField(upload_to='images/', validators=[entertainments.validators.image_validation_extension])),
                ('entertainmentOption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainments.EntertainmentOption')),
            ],
        ),
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=250)),
                ('comedian', models.CharField(max_length=250)),
                ('released_date', models.DateField()),
                ('distribution_rights', models.TextField()),
                ('about_jokes', models.TextField()),
                ('commic_genre', models.CharField(choices=[('L', 'Life Advice'), ('F', 'Personal Finance'), ('A', 'Academic Performance'), ('O', 'Other')], default='Other', max_length=60)),
                ('cover_image', models.ImageField(upload_to='images/', validators=[entertainments.validators.image_validation_extension])),
                ('upload_comedy', models.FileField(upload_to='audios/', validators=[entertainments.validators.video_validation_extention])),
                ('entertainmentOption', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entertainments.EntertainmentOption')),
            ],
        ),
    ]
