# Generated by Django 2.2 on 2019-06-15 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import entertainments.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='upload_comedy',
            field=models.FileField(upload_to='audios/', validators=[entertainments.validators.video_validation_extention]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie',
            field=models.FileField(upload_to='videos/', validators=[entertainments.validators.video_validation_extention]),
        ),
        migrations.CreateModel(
            name='CommunityContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('thumbnail', models.ImageField(upload_to='images/community', validators=[entertainments.validators.image_validation_extension])),
                ('video', models.FileField(upload_to='audios/community', validators=[entertainments.validators.video_validation_extention])),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
