# Generated by Django 2.2 on 2019-06-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedy',
            name='entertainmentOption',
        ),
        migrations.RemoveField(
            model_name='entertainmentoption',
            name='allowed_plans',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='entertainmentOption',
        ),
        migrations.RemoveField(
            model_name='music',
            name='entertainmentOption',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='entertainmentOption',
        ),
    ]
