# Generated by Django 2.2 on 2019-06-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0002_auto_20190615_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycontent',
            name='user',
        ),
    ]
