# Generated by Django 2.2 on 2019-06-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0002_auto_20190613_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntertainmentOption',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='song_name',
            new_name='song_title',
        ),
        migrations.RenameField(
            model_name='podcast',
            old_name='song_name',
            new_name='podcast_name',
        ),
        migrations.RemoveField(
            model_name='comedy',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='music',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='slug',
        ),
    ]
