# Generated by Django 2.2 on 2019-06-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0003_auto_20190613_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedy',
            name='commic_genre',
        ),
    ]
