# Generated by Django 2.2 on 2019-06-13 22:14

from django.db import migrations, models
import entertainments.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurnerSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=30)),
                ('background_image', models.ImageField(upload_to='customer_profiles/', validators=[entertainments.validators.image_validation_extension])),
                ('main_message', models.TextField()),
                ('button_message', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.TextField()),
                ('right', models.TextField()),
                ('center', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=140)),
                ('cover_image', models.ImageField(upload_to='customer_profiles/', validators=[entertainments.validators.image_validation_extension])),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrendingAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_title', models.CharField(max_length=40)),
                ('heading', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('button_message', models.CharField(max_length=30)),
            ],
        ),
    ]
