# Generated by Django 2.2 on 2019-06-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burnerslide',
            old_name='background_image',
            new_name='background_svg',
        ),
    ]
