# Generated by Django 2.2 on 2019-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burnerslide',
            name='button_message',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='footer',
            name='center',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='left',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='right',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='headline',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='trendingad',
            name='button_message',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trendingad',
            name='circle_title',
            field=models.CharField(max_length=40),
        ),
    ]
