# Generated by Django 2.2 on 2019-06-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='istream_options',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
